# Site settings
url: https://sifsuska.github.io # the base hostname & protocol for your site
baseurl: /jekyll-angular-demo/ # the subpath of your site, e.g. /blog/

title: Reported Observations of Aquatic Invasive Species
email: kampar@gmail.com
description: "A simple angular app that uses Google Maps and Open Data"
github_username:  sifsuska

# Build settings
markdown: kramdown
